/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IPoolFactory, IPoolFactoryInterface } from "../IPoolFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "autoClaim",
        type: "address",
      },
    ],
    name: "AutoClaimChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "poolCommitterAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "settlementToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "changeInterval",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "feeController",
        type: "address",
      },
    ],
    name: "DeployCommitter",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "poolCommitter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "ticker",
        type: "string",
      },
    ],
    name: "DeployPool",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "FeeChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "FeeReceiverChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "invariantCheck",
        type: "address",
      },
    ],
    name: "InvariantCheckChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "leverage",
        type: "uint256",
      },
    ],
    name: "MaxLeverageChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "mint",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "burn",
        type: "uint256",
      },
    ],
    name: "MintAndBurnFeesChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_poolKeeper",
        type: "address",
      },
    ],
    name: "PoolKeeperChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
    ],
    name: "SecondaryFeeSplitChanged",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "poolName",
            type: "string",
          },
          {
            internalType: "uint32",
            name: "frontRunningInterval",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "updateInterval",
            type: "uint32",
          },
          {
            internalType: "uint16",
            name: "leverageAmount",
            type: "uint16",
          },
          {
            internalType: "address",
            name: "settlementToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "oracleWrapper",
            type: "address",
          },
          {
            internalType: "address",
            name: "settlementEthOracle",
            type: "address",
          },
          {
            internalType: "address",
            name: "feeController",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "mintingFee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "changeInterval",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "burningFee",
            type: "uint256",
          },
        ],
        internalType: "struct IPoolFactory.PoolDeployment",
        name: "deploymentParameters",
        type: "tuple",
      },
    ],
    name: "deployPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pool",
        type: "address",
      },
    ],
    name: "isValidPool",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_poolCommitter",
        type: "address",
      },
    ],
    name: "isValidPoolCommitter",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numPools",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "pools",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_autoClaim",
        type: "address",
      },
    ],
    name: "setAutoClaim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_fee",
        type: "uint256",
      },
    ],
    name: "setFee",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_feeReceiver",
        type: "address",
      },
    ],
    name: "setFeeReceiver",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_invariantCheck",
        type: "address",
      },
    ],
    name: "setInvariantCheck",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_poolKeeper",
        type: "address",
      },
    ],
    name: "setPoolKeeper",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newFeePercent",
        type: "uint256",
      },
    ],
    name: "setSecondaryFeeSplitPercent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPoolFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPoolFactoryInterface {
    return new utils.Interface(_abi) as IPoolFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPoolFactory {
    return new Contract(address, _abi, signerOrProvider) as IPoolFactory;
  }
}
