/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface L2EncoderInterface extends ethers.utils.Interface {
  functions: {
    "encodeAddressArray(address[])": FunctionFragment;
    "encodeCommitParams(uint256,uint8,bool,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "encodeAddressArray",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeCommitParams",
    values: [BigNumberish, BigNumberish, boolean, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "encodeAddressArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeCommitParams",
    data: BytesLike
  ): Result;

  events: {};
}

export class L2Encoder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: L2EncoderInterface;

  functions: {
    encodeAddressArray(
      args: string[],
      overrides?: CallOverrides
    ): Promise<[string]>;

    encodeCommitParams(
      amount: BigNumberish,
      commitType: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  encodeAddressArray(
    args: string[],
    overrides?: CallOverrides
  ): Promise<string>;

  encodeCommitParams(
    amount: BigNumberish,
    commitType: BigNumberish,
    fromAggregateBalance: boolean,
    payForClaim: boolean,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    encodeAddressArray(
      args: string[],
      overrides?: CallOverrides
    ): Promise<string>;

    encodeCommitParams(
      amount: BigNumberish,
      commitType: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    encodeAddressArray(
      args: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    encodeCommitParams(
      amount: BigNumberish,
      commitType: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    encodeAddressArray(
      args: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    encodeCommitParams(
      amount: BigNumberish,
      commitType: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
