/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PoolKeeperInterface extends ethers.utils.Interface {
  functions: {
    "checkUpkeepMultiplePools(address[])": FunctionFragment;
    "executionPrice(address)": FunctionFragment;
    "factory()": FunctionFragment;
    "gasPrice()": FunctionFragment;
    "isUpkeepRequiredSinglePool(address)": FunctionFragment;
    "keeperRewards()": FunctionFragment;
    "newPool(address)": FunctionFragment;
    "owner()": FunctionFragment;
    "performUpkeepMultiplePools(address[])": FunctionFragment;
    "performUpkeepMultiplePoolsPacked(bytes)": FunctionFragment;
    "performUpkeepSinglePool(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setGasPrice(uint256)": FunctionFragment;
    "setKeeperRewards(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkUpkeepMultiplePools",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executionPrice",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "gasPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isUpkeepRequiredSinglePool",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "keeperRewards",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "newPool", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "performUpkeepMultiplePools",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeepMultiplePoolsPacked",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeepSinglePool",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGasPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setKeeperRewards",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkUpkeepMultiplePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gasPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isUpkeepRequiredSinglePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "keeperRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "newPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeepMultiplePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeepMultiplePoolsPacked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeepSinglePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKeeperRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "FactoryChanged(address)": EventFragment;
    "GasPriceChanged(uint256)": EventFragment;
    "KeeperPaid(address,address,uint256)": EventFragment;
    "KeeperPaymentError(address,address,uint256)": EventFragment;
    "KeeperRewardsSet(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PoolAdded(address,int256)": EventFragment;
    "PoolUpkeepError(address,string)": EventFragment;
    "UpkeepSuccessful(address,bytes,int256,int256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "FactoryChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GasPriceChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "KeeperPaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "KeeperPaymentError"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "KeeperRewardsSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolUpkeepError"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpkeepSuccessful"): EventFragment;
}

export class PoolKeeper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PoolKeeperInterface;

  functions: {
    checkUpkeepMultiplePools(
      _pools: string[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    executionPrice(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    gasPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    isUpkeepRequiredSinglePool(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    keeperRewards(overrides?: CallOverrides): Promise<[string]>;

    newPool(
      _poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    performUpkeepMultiplePools(
      pools: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    performUpkeepMultiplePoolsPacked(
      pools: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    performUpkeepSinglePool(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGasPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setKeeperRewards(
      _keeperRewards: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  checkUpkeepMultiplePools(
    _pools: string[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  executionPrice(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  factory(overrides?: CallOverrides): Promise<string>;

  gasPrice(overrides?: CallOverrides): Promise<BigNumber>;

  isUpkeepRequiredSinglePool(
    _pool: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  keeperRewards(overrides?: CallOverrides): Promise<string>;

  newPool(
    _poolAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  performUpkeepMultiplePools(
    pools: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  performUpkeepMultiplePoolsPacked(
    pools: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  performUpkeepSinglePool(
    _pool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGasPrice(
    _price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setKeeperRewards(
    _keeperRewards: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    checkUpkeepMultiplePools(
      _pools: string[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    executionPrice(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<string>;

    gasPrice(overrides?: CallOverrides): Promise<BigNumber>;

    isUpkeepRequiredSinglePool(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    keeperRewards(overrides?: CallOverrides): Promise<string>;

    newPool(_poolAddress: string, overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    performUpkeepMultiplePools(
      pools: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    performUpkeepMultiplePoolsPacked(
      pools: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    performUpkeepSinglePool(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setGasPrice(_price: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setKeeperRewards(
      _keeperRewards: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    FactoryChanged(
      factory?: string | null
    ): TypedEventFilter<[string], { factory: string }>;

    GasPriceChanged(
      price?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { price: BigNumber }>;

    KeeperPaid(
      _pool?: string | null,
      keeper?: string | null,
      reward?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { _pool: string; keeper: string; reward: BigNumber }
    >;

    KeeperPaymentError(
      _pool?: string | null,
      keeper?: string | null,
      expectedReward?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { _pool: string; keeper: string; expectedReward: BigNumber }
    >;

    KeeperRewardsSet(
      oldKeeperRewards?: string | null,
      newKeeperRewards?: string | null
    ): TypedEventFilter<
      [string, string],
      { oldKeeperRewards: string; newKeeperRewards: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    PoolAdded(
      poolAddress?: string | null,
      firstPrice?: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber],
      { poolAddress: string; firstPrice: BigNumber }
    >;

    PoolUpkeepError(
      pool?: string | null,
      reason?: null
    ): TypedEventFilter<[string, string], { pool: string; reason: string }>;

    UpkeepSuccessful(
      pool?: string | null,
      data?: null,
      startPrice?: BigNumberish | null,
      endPrice?: BigNumberish | null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber],
      { pool: string; data: string; startPrice: BigNumber; endPrice: BigNumber }
    >;
  };

  estimateGas: {
    checkUpkeepMultiplePools(
      _pools: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    executionPrice(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    gasPrice(overrides?: CallOverrides): Promise<BigNumber>;

    isUpkeepRequiredSinglePool(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    keeperRewards(overrides?: CallOverrides): Promise<BigNumber>;

    newPool(
      _poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    performUpkeepMultiplePools(
      pools: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    performUpkeepMultiplePoolsPacked(
      pools: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    performUpkeepSinglePool(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGasPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setKeeperRewards(
      _keeperRewards: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkUpkeepMultiplePools(
      _pools: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    executionPrice(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    gasPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isUpkeepRequiredSinglePool(
      _pool: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    keeperRewards(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newPool(
      _poolAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    performUpkeepMultiplePools(
      pools: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    performUpkeepMultiplePoolsPacked(
      pools: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    performUpkeepSinglePool(
      _pool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGasPrice(
      _price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setKeeperRewards(
      _keeperRewards: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
