/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PoolCommitterInterface extends ethers.utils.Interface {
  functions: {
    "LONG_INDEX()": FunctionFragment;
    "MAX_ITERATIONS()": FunctionFragment;
    "SHORT_INDEX()": FunctionFragment;
    "autoClaim()": FunctionFragment;
    "burnFeeHistory(uint256)": FunctionFragment;
    "burningFee()": FunctionFragment;
    "changeInterval()": FunctionFragment;
    "claim(address)": FunctionFragment;
    "commit(uint8,uint256,bool,bool)": FunctionFragment;
    "executeCommitments(uint256,uint256,uint256,uint256)": FunctionFragment;
    "factory()": FunctionFragment;
    "feeController()": FunctionFragment;
    "getAggregateBalance(address)": FunctionFragment;
    "getAppropriateUpdateIntervalId()": FunctionFragment;
    "getBurningFee()": FunctionFragment;
    "getMintingFee()": FunctionFragment;
    "governance()": FunctionFragment;
    "initialize(address,address,address,address,address,uint256,uint256,uint256)": FunctionFragment;
    "invariantCheck()": FunctionFragment;
    "lastUpdatedIntervalId(address)": FunctionFragment;
    "leveragedPool()": FunctionFragment;
    "mintingFee()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "pendingLongBurnPoolTokens()": FunctionFragment;
    "pendingMintSettlementAmount()": FunctionFragment;
    "pendingShortBurnPoolTokens()": FunctionFragment;
    "priceHistory(uint256)": FunctionFragment;
    "setBurningFee(uint256)": FunctionFragment;
    "setChangeInterval(uint256)": FunctionFragment;
    "setFeeController(address)": FunctionFragment;
    "setMintingFee(uint256)": FunctionFragment;
    "setPool(address)": FunctionFragment;
    "tokens(uint256)": FunctionFragment;
    "totalPoolCommitments(uint256)": FunctionFragment;
    "unAggregatedCommitments(address,uint256)": FunctionFragment;
    "unpause()": FunctionFragment;
    "updateAggregateBalance(address)": FunctionFragment;
    "updateIntervalId()": FunctionFragment;
    "userAggregateBalance(address)": FunctionFragment;
    "userCommitments(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "LONG_INDEX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ITERATIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHORT_INDEX",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "autoClaim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "burnFeeHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burningFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeInterval",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [string]): string;
  encodeFunctionData(
    functionFragment: "commit",
    values: [BigNumberish, BigNumberish, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "executeCommitments",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAggregateBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAppropriateUpdateIntervalId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBurningFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMintingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "invariantCheck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastUpdatedIntervalId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "leveragedPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintingFee",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingLongBurnPoolTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingMintSettlementAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingShortBurnPoolTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "priceHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBurningFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setChangeInterval",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintingFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setPool", values: [string]): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPoolCommitments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unAggregatedCommitments",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAggregateBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIntervalId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userAggregateBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userCommitments",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "LONG_INDEX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ITERATIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SHORT_INDEX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "autoClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnFeeHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burningFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "commit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAggregateBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAppropriateUpdateIntervalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBurningFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMintingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "invariantCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastUpdatedIntervalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leveragedPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintingFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingLongBurnPoolTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingMintSettlementAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingShortBurnPoolTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBurningFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChangeInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMintingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPoolCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unAggregatedCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAggregateBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIntervalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userAggregateBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCommitments",
    data: BytesLike
  ): Result;

  events: {
    "AggregateBalanceUpdated(address)": EventFragment;
    "BurningFeeSet(uint256)": EventFragment;
    "ChangeIntervalSet(uint256)": EventFragment;
    "Claim(address)": EventFragment;
    "CreateCommit(address,uint256,uint8,uint256,bool,bool,bytes16)": EventFragment;
    "ExecutedCommitsForInterval(uint256,bytes16)": EventFragment;
    "FeeControllerSet(address)": EventFragment;
    "MintingFeeSet(uint256)": EventFragment;
    "Paused()": EventFragment;
    "Unpaused()": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AggregateBalanceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BurningFeeSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChangeIntervalSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateCommit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutedCommitsForInterval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeControllerSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintingFeeSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export class PoolCommitter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PoolCommitterInterface;

  functions: {
    LONG_INDEX(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_ITERATIONS(overrides?: CallOverrides): Promise<[number]>;

    SHORT_INDEX(overrides?: CallOverrides): Promise<[BigNumber]>;

    autoClaim(overrides?: CallOverrides): Promise<[string]>;

    burnFeeHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    burningFee(overrides?: CallOverrides): Promise<[string]>;

    changeInterval(overrides?: CallOverrides): Promise<[string]>;

    claim(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeCommitments(
      lastPriceTimestamp: BigNumberish,
      updateInterval: BigNumberish,
      longBalance: BigNumberish,
      shortBalance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    feeController(overrides?: CallOverrides): Promise<[string]>;

    getAggregateBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber] & {
          longTokens: BigNumber;
          shortTokens: BigNumber;
          settlementTokens: BigNumber;
        }
      ]
    >;

    getAppropriateUpdateIntervalId(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getBurningFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMintingFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    governance(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      _factory: string,
      _autoClaim: string,
      _factoryOwner: string,
      _feeController: string,
      _invariantCheck: string,
      _mintingFee: BigNumberish,
      _burningFee: BigNumberish,
      _changeInterval: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    invariantCheck(overrides?: CallOverrides): Promise<[string]>;

    lastUpdatedIntervalId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    leveragedPool(overrides?: CallOverrides): Promise<[string]>;

    mintingFee(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    pendingLongBurnPoolTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    pendingMintSettlementAmount(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    pendingShortBurnPoolTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    priceHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { longPrice: string; shortPrice: string }>;

    setBurningFee(
      _burningFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setChangeInterval(
      _changeInterval: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFeeController(
      _feeController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMintingFee(
      _mintingFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPool(
      _leveragedPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    totalPoolCommitments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        longMintSettlement: BigNumber;
        longBurnPoolTokens: BigNumber;
        shortMintSettlement: BigNumber;
        shortBurnPoolTokens: BigNumber;
        shortBurnLongMintPoolTokens: BigNumber;
        longBurnShortMintPoolTokens: BigNumber;
        updateIntervalId: BigNumber;
      }
    >;

    unAggregatedCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateAggregateBalance(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateIntervalId(overrides?: CallOverrides): Promise<[BigNumber]>;

    userAggregateBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        longTokens: BigNumber;
        shortTokens: BigNumber;
        settlementTokens: BigNumber;
      }
    >;

    userCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        longMintSettlement: BigNumber;
        longBurnPoolTokens: BigNumber;
        balanceLongBurnPoolTokens: BigNumber;
        shortMintSettlement: BigNumber;
        shortBurnPoolTokens: BigNumber;
        balanceShortBurnPoolTokens: BigNumber;
        shortBurnLongMintPoolTokens: BigNumber;
        balanceShortBurnMintPoolTokens: BigNumber;
        longBurnShortMintPoolTokens: BigNumber;
        balanceLongBurnMintPoolTokens: BigNumber;
        updateIntervalId: BigNumber;
      }
    >;
  };

  LONG_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_ITERATIONS(overrides?: CallOverrides): Promise<number>;

  SHORT_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

  autoClaim(overrides?: CallOverrides): Promise<string>;

  burnFeeHistory(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  burningFee(overrides?: CallOverrides): Promise<string>;

  changeInterval(overrides?: CallOverrides): Promise<string>;

  claim(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  commit(
    commitType: BigNumberish,
    amount: BigNumberish,
    fromAggregateBalance: boolean,
    payForClaim: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeCommitments(
    lastPriceTimestamp: BigNumberish,
    updateInterval: BigNumberish,
    longBalance: BigNumberish,
    shortBalance: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  feeController(overrides?: CallOverrides): Promise<string>;

  getAggregateBalance(
    user: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      longTokens: BigNumber;
      shortTokens: BigNumber;
      settlementTokens: BigNumber;
    }
  >;

  getAppropriateUpdateIntervalId(overrides?: CallOverrides): Promise<BigNumber>;

  getBurningFee(overrides?: CallOverrides): Promise<BigNumber>;

  getMintingFee(overrides?: CallOverrides): Promise<BigNumber>;

  governance(overrides?: CallOverrides): Promise<string>;

  initialize(
    _factory: string,
    _autoClaim: string,
    _factoryOwner: string,
    _feeController: string,
    _invariantCheck: string,
    _mintingFee: BigNumberish,
    _burningFee: BigNumberish,
    _changeInterval: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  invariantCheck(overrides?: CallOverrides): Promise<string>;

  lastUpdatedIntervalId(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  leveragedPool(overrides?: CallOverrides): Promise<string>;

  mintingFee(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  pendingLongBurnPoolTokens(overrides?: CallOverrides): Promise<BigNumber>;

  pendingMintSettlementAmount(overrides?: CallOverrides): Promise<BigNumber>;

  pendingShortBurnPoolTokens(overrides?: CallOverrides): Promise<BigNumber>;

  priceHistory(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string] & { longPrice: string; shortPrice: string }>;

  setBurningFee(
    _burningFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setChangeInterval(
    _changeInterval: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFeeController(
    _feeController: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMintingFee(
    _mintingFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPool(
    _leveragedPool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  totalPoolCommitments(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      longMintSettlement: BigNumber;
      longBurnPoolTokens: BigNumber;
      shortMintSettlement: BigNumber;
      shortBurnPoolTokens: BigNumber;
      shortBurnLongMintPoolTokens: BigNumber;
      longBurnShortMintPoolTokens: BigNumber;
      updateIntervalId: BigNumber;
    }
  >;

  unAggregatedCommitments(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateAggregateBalance(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateIntervalId(overrides?: CallOverrides): Promise<BigNumber>;

  userAggregateBalance(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      longTokens: BigNumber;
      shortTokens: BigNumber;
      settlementTokens: BigNumber;
    }
  >;

  userCommitments(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      longMintSettlement: BigNumber;
      longBurnPoolTokens: BigNumber;
      balanceLongBurnPoolTokens: BigNumber;
      shortMintSettlement: BigNumber;
      shortBurnPoolTokens: BigNumber;
      balanceShortBurnPoolTokens: BigNumber;
      shortBurnLongMintPoolTokens: BigNumber;
      balanceShortBurnMintPoolTokens: BigNumber;
      longBurnShortMintPoolTokens: BigNumber;
      balanceLongBurnMintPoolTokens: BigNumber;
      updateIntervalId: BigNumber;
    }
  >;

  callStatic: {
    LONG_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_ITERATIONS(overrides?: CallOverrides): Promise<number>;

    SHORT_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    autoClaim(overrides?: CallOverrides): Promise<string>;

    burnFeeHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    burningFee(overrides?: CallOverrides): Promise<string>;

    changeInterval(overrides?: CallOverrides): Promise<string>;

    claim(user: string, overrides?: CallOverrides): Promise<void>;

    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    executeCommitments(
      lastPriceTimestamp: BigNumberish,
      updateInterval: BigNumberish,
      longBalance: BigNumberish,
      shortBalance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber, BigNumber, BigNumber]>;

    factory(overrides?: CallOverrides): Promise<string>;

    feeController(overrides?: CallOverrides): Promise<string>;

    getAggregateBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        longTokens: BigNumber;
        shortTokens: BigNumber;
        settlementTokens: BigNumber;
      }
    >;

    getAppropriateUpdateIntervalId(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBurningFee(overrides?: CallOverrides): Promise<BigNumber>;

    getMintingFee(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<string>;

    initialize(
      _factory: string,
      _autoClaim: string,
      _factoryOwner: string,
      _feeController: string,
      _invariantCheck: string,
      _mintingFee: BigNumberish,
      _burningFee: BigNumberish,
      _changeInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    invariantCheck(overrides?: CallOverrides): Promise<string>;

    lastUpdatedIntervalId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    leveragedPool(overrides?: CallOverrides): Promise<string>;

    mintingFee(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    pendingLongBurnPoolTokens(overrides?: CallOverrides): Promise<BigNumber>;

    pendingMintSettlementAmount(overrides?: CallOverrides): Promise<BigNumber>;

    pendingShortBurnPoolTokens(overrides?: CallOverrides): Promise<BigNumber>;

    priceHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { longPrice: string; shortPrice: string }>;

    setBurningFee(
      _burningFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setChangeInterval(
      _changeInterval: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeController(
      _feeController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMintingFee(
      _mintingFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setPool(_leveragedPool: string, overrides?: CallOverrides): Promise<void>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    totalPoolCommitments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        longMintSettlement: BigNumber;
        longBurnPoolTokens: BigNumber;
        shortMintSettlement: BigNumber;
        shortBurnPoolTokens: BigNumber;
        shortBurnLongMintPoolTokens: BigNumber;
        longBurnShortMintPoolTokens: BigNumber;
        updateIntervalId: BigNumber;
      }
    >;

    unAggregatedCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updateAggregateBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateIntervalId(overrides?: CallOverrides): Promise<BigNumber>;

    userAggregateBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        longTokens: BigNumber;
        shortTokens: BigNumber;
        settlementTokens: BigNumber;
      }
    >;

    userCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        longMintSettlement: BigNumber;
        longBurnPoolTokens: BigNumber;
        balanceLongBurnPoolTokens: BigNumber;
        shortMintSettlement: BigNumber;
        shortBurnPoolTokens: BigNumber;
        balanceShortBurnPoolTokens: BigNumber;
        shortBurnLongMintPoolTokens: BigNumber;
        balanceShortBurnMintPoolTokens: BigNumber;
        longBurnShortMintPoolTokens: BigNumber;
        balanceLongBurnMintPoolTokens: BigNumber;
        updateIntervalId: BigNumber;
      }
    >;
  };

  filters: {
    AggregateBalanceUpdated(
      user?: string | null
    ): TypedEventFilter<[string], { user: string }>;

    BurningFeeSet(
      _burningFee?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _burningFee: BigNumber }>;

    ChangeIntervalSet(
      _changeInterval?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _changeInterval: BigNumber }>;

    Claim(user?: string | null): TypedEventFilter<[string], { user: string }>;

    CreateCommit(
      user?: string | null,
      amount?: BigNumberish | null,
      commitType?: BigNumberish | null,
      appropriateUpdateIntervalId?: null,
      fromAggregateBalance?: null,
      payForClaim?: null,
      mintingFee?: null
    ): TypedEventFilter<
      [string, BigNumber, number, BigNumber, boolean, boolean, string],
      {
        user: string;
        amount: BigNumber;
        commitType: number;
        appropriateUpdateIntervalId: BigNumber;
        fromAggregateBalance: boolean;
        payForClaim: boolean;
        mintingFee: string;
      }
    >;

    ExecutedCommitsForInterval(
      updateIntervalId?: BigNumberish | null,
      burningFee?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { updateIntervalId: BigNumber; burningFee: string }
    >;

    FeeControllerSet(
      _feeController?: string | null
    ): TypedEventFilter<[string], { _feeController: string }>;

    MintingFeeSet(
      _mintingFee?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { _mintingFee: BigNumber }>;

    Paused(): TypedEventFilter<[], {}>;

    Unpaused(): TypedEventFilter<[], {}>;
  };

  estimateGas: {
    LONG_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_ITERATIONS(overrides?: CallOverrides): Promise<BigNumber>;

    SHORT_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    autoClaim(overrides?: CallOverrides): Promise<BigNumber>;

    burnFeeHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burningFee(overrides?: CallOverrides): Promise<BigNumber>;

    changeInterval(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeCommitments(
      lastPriceTimestamp: BigNumberish,
      updateInterval: BigNumberish,
      longBalance: BigNumberish,
      shortBalance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    feeController(overrides?: CallOverrides): Promise<BigNumber>;

    getAggregateBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAppropriateUpdateIntervalId(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBurningFee(overrides?: CallOverrides): Promise<BigNumber>;

    getMintingFee(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _factory: string,
      _autoClaim: string,
      _factoryOwner: string,
      _feeController: string,
      _invariantCheck: string,
      _mintingFee: BigNumberish,
      _burningFee: BigNumberish,
      _changeInterval: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    invariantCheck(overrides?: CallOverrides): Promise<BigNumber>;

    lastUpdatedIntervalId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    leveragedPool(overrides?: CallOverrides): Promise<BigNumber>;

    mintingFee(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    pendingLongBurnPoolTokens(overrides?: CallOverrides): Promise<BigNumber>;

    pendingMintSettlementAmount(overrides?: CallOverrides): Promise<BigNumber>;

    pendingShortBurnPoolTokens(overrides?: CallOverrides): Promise<BigNumber>;

    priceHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBurningFee(
      _burningFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setChangeInterval(
      _changeInterval: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFeeController(
      _feeController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMintingFee(
      _mintingFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPool(
      _leveragedPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    totalPoolCommitments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unAggregatedCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateAggregateBalance(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateIntervalId(overrides?: CallOverrides): Promise<BigNumber>;

    userAggregateBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    LONG_INDEX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MAX_ITERATIONS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SHORT_INDEX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    autoClaim(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    burnFeeHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    burningFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeInterval(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claim(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeCommitments(
      lastPriceTimestamp: BigNumberish,
      updateInterval: BigNumberish,
      longBalance: BigNumberish,
      shortBalance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeController(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAggregateBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAppropriateUpdateIntervalId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBurningFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMintingFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _factory: string,
      _autoClaim: string,
      _factoryOwner: string,
      _feeController: string,
      _invariantCheck: string,
      _mintingFee: BigNumberish,
      _burningFee: BigNumberish,
      _changeInterval: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    invariantCheck(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastUpdatedIntervalId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    leveragedPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintingFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingLongBurnPoolTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingMintSettlementAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingShortBurnPoolTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    priceHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setBurningFee(
      _burningFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setChangeInterval(
      _changeInterval: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFeeController(
      _feeController: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMintingFee(
      _mintingFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPool(
      _leveragedPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalPoolCommitments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unAggregatedCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateAggregateBalance(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateIntervalId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    userAggregateBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
