/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PoolFactoryBalanceDrainMockInterface extends ethers.utils.Interface {
  functions: {
    "autoClaim()": FunctionFragment;
    "claimGovernance()": FunctionFragment;
    "deployPool(tuple)": FunctionFragment;
    "fee()": FunctionFragment;
    "feeReceiver()": FunctionFragment;
    "governance()": FunctionFragment;
    "governanceTransferInProgress()": FunctionFragment;
    "invariantCheck()": FunctionFragment;
    "isValidPool(address)": FunctionFragment;
    "isValidPoolCommitter(address)": FunctionFragment;
    "numPools()": FunctionFragment;
    "pairTokenBaseAddress()": FunctionFragment;
    "poolBaseAddress()": FunctionFragment;
    "poolCommitterBaseAddress()": FunctionFragment;
    "poolKeeper()": FunctionFragment;
    "pools(uint256)": FunctionFragment;
    "provisionalGovernance()": FunctionFragment;
    "secondaryFeeSplitPercent()": FunctionFragment;
    "setAutoClaim(address)": FunctionFragment;
    "setFee(uint256)": FunctionFragment;
    "setFeeReceiver(address)": FunctionFragment;
    "setInvariantCheck(address)": FunctionFragment;
    "setPoolKeeper(address)": FunctionFragment;
    "setSecondaryFeeSplitPercent(uint256)": FunctionFragment;
    "transferGovernance(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "autoClaim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deployPool",
    values: [
      {
        poolName: string;
        frontRunningInterval: BigNumberish;
        updateInterval: BigNumberish;
        leverageAmount: BigNumberish;
        settlementToken: string;
        oracleWrapper: string;
        settlementEthOracle: string;
        feeController: string;
        mintingFee: BigNumberish;
        changeInterval: BigNumberish;
        burningFee: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "fee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governanceTransferInProgress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invariantCheck",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isValidPool", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isValidPoolCommitter",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "numPools", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pairTokenBaseAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolBaseAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolCommitterBaseAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolKeeper",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pools", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "provisionalGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "secondaryFeeSplitPercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAutoClaim",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeReceiver",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setInvariantCheck",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolKeeper",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSecondaryFeeSplitPercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferGovernance",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "autoClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "governanceTransferInProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invariantCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidPoolCommitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "numPools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pairTokenBaseAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolBaseAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolCommitterBaseAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolKeeper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "provisionalGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "secondaryFeeSplitPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutoClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setInvariantCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolKeeper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSecondaryFeeSplitPercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferGovernance",
    data: BytesLike
  ): Result;

  events: {
    "AutoClaimChanged(address)": EventFragment;
    "DeployCommitter(address,address,address,uint256,address)": EventFragment;
    "DeployPool(address,address,string)": EventFragment;
    "FeeChanged(uint256)": EventFragment;
    "FeeReceiverChanged(address)": EventFragment;
    "GovernanceAddressChanged(address,address)": EventFragment;
    "InvariantCheckChanged(address)": EventFragment;
    "MaxLeverageChanged(uint256)": EventFragment;
    "MintAndBurnFeesChanged(uint256,uint256)": EventFragment;
    "PoolKeeperChanged(address)": EventFragment;
    "ProvisionalGovernanceChanged(address)": EventFragment;
    "SecondaryFeeSplitChanged(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AutoClaimChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeployCommitter"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeployPool"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FeeReceiverChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernanceAddressChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InvariantCheckChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MaxLeverageChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintAndBurnFeesChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PoolKeeperChanged"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ProvisionalGovernanceChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SecondaryFeeSplitChanged"): EventFragment;
}

export class PoolFactoryBalanceDrainMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PoolFactoryBalanceDrainMockInterface;

  functions: {
    autoClaim(overrides?: CallOverrides): Promise<[string]>;

    claimGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployPool(
      deploymentParameters: {
        poolName: string;
        frontRunningInterval: BigNumberish;
        updateInterval: BigNumberish;
        leverageAmount: BigNumberish;
        settlementToken: string;
        oracleWrapper: string;
        settlementEthOracle: string;
        feeController: string;
        mintingFee: BigNumberish;
        changeInterval: BigNumberish;
        burningFee: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fee(overrides?: CallOverrides): Promise<[BigNumber]>;

    feeReceiver(overrides?: CallOverrides): Promise<[string]>;

    governance(overrides?: CallOverrides): Promise<[string]>;

    governanceTransferInProgress(overrides?: CallOverrides): Promise<[boolean]>;

    invariantCheck(overrides?: CallOverrides): Promise<[string]>;

    isValidPool(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    isValidPoolCommitter(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    numPools(overrides?: CallOverrides): Promise<[BigNumber]>;

    pairTokenBaseAddress(overrides?: CallOverrides): Promise<[string]>;

    poolBaseAddress(overrides?: CallOverrides): Promise<[string]>;

    poolCommitterBaseAddress(overrides?: CallOverrides): Promise<[string]>;

    poolKeeper(overrides?: CallOverrides): Promise<[string]>;

    pools(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    provisionalGovernance(overrides?: CallOverrides): Promise<[string]>;

    secondaryFeeSplitPercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    setAutoClaim(
      _autoClaim: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFee(
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFeeReceiver(
      _feeReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setInvariantCheck(
      _invariantCheck: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPoolKeeper(
      _poolKeeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSecondaryFeeSplitPercent(
      newFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferGovernance(
      _governance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  autoClaim(overrides?: CallOverrides): Promise<string>;

  claimGovernance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployPool(
    deploymentParameters: {
      poolName: string;
      frontRunningInterval: BigNumberish;
      updateInterval: BigNumberish;
      leverageAmount: BigNumberish;
      settlementToken: string;
      oracleWrapper: string;
      settlementEthOracle: string;
      feeController: string;
      mintingFee: BigNumberish;
      changeInterval: BigNumberish;
      burningFee: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fee(overrides?: CallOverrides): Promise<BigNumber>;

  feeReceiver(overrides?: CallOverrides): Promise<string>;

  governance(overrides?: CallOverrides): Promise<string>;

  governanceTransferInProgress(overrides?: CallOverrides): Promise<boolean>;

  invariantCheck(overrides?: CallOverrides): Promise<string>;

  isValidPool(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  isValidPoolCommitter(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  numPools(overrides?: CallOverrides): Promise<BigNumber>;

  pairTokenBaseAddress(overrides?: CallOverrides): Promise<string>;

  poolBaseAddress(overrides?: CallOverrides): Promise<string>;

  poolCommitterBaseAddress(overrides?: CallOverrides): Promise<string>;

  poolKeeper(overrides?: CallOverrides): Promise<string>;

  pools(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  provisionalGovernance(overrides?: CallOverrides): Promise<string>;

  secondaryFeeSplitPercent(overrides?: CallOverrides): Promise<BigNumber>;

  setAutoClaim(
    _autoClaim: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFee(
    _fee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFeeReceiver(
    _feeReceiver: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setInvariantCheck(
    _invariantCheck: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPoolKeeper(
    _poolKeeper: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSecondaryFeeSplitPercent(
    newFeePercent: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferGovernance(
    _governance: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    autoClaim(overrides?: CallOverrides): Promise<string>;

    claimGovernance(overrides?: CallOverrides): Promise<void>;

    deployPool(
      deploymentParameters: {
        poolName: string;
        frontRunningInterval: BigNumberish;
        updateInterval: BigNumberish;
        leverageAmount: BigNumberish;
        settlementToken: string;
        oracleWrapper: string;
        settlementEthOracle: string;
        feeController: string;
        mintingFee: BigNumberish;
        changeInterval: BigNumberish;
        burningFee: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    feeReceiver(overrides?: CallOverrides): Promise<string>;

    governance(overrides?: CallOverrides): Promise<string>;

    governanceTransferInProgress(overrides?: CallOverrides): Promise<boolean>;

    invariantCheck(overrides?: CallOverrides): Promise<string>;

    isValidPool(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    isValidPoolCommitter(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    numPools(overrides?: CallOverrides): Promise<BigNumber>;

    pairTokenBaseAddress(overrides?: CallOverrides): Promise<string>;

    poolBaseAddress(overrides?: CallOverrides): Promise<string>;

    poolCommitterBaseAddress(overrides?: CallOverrides): Promise<string>;

    poolKeeper(overrides?: CallOverrides): Promise<string>;

    pools(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    provisionalGovernance(overrides?: CallOverrides): Promise<string>;

    secondaryFeeSplitPercent(overrides?: CallOverrides): Promise<BigNumber>;

    setAutoClaim(_autoClaim: string, overrides?: CallOverrides): Promise<void>;

    setFee(_fee: BigNumberish, overrides?: CallOverrides): Promise<void>;

    setFeeReceiver(
      _feeReceiver: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setInvariantCheck(
      _invariantCheck: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setPoolKeeper(
      _poolKeeper: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSecondaryFeeSplitPercent(
      newFeePercent: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    transferGovernance(
      _governance: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    AutoClaimChanged(
      autoClaim?: string | null
    ): TypedEventFilter<[string], { autoClaim: string }>;

    DeployCommitter(
      poolCommitterAddress?: null,
      settlementToken?: null,
      pool?: null,
      changeInterval?: null,
      feeController?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, string],
      {
        poolCommitterAddress: string;
        settlementToken: string;
        pool: string;
        changeInterval: BigNumber;
        feeController: string;
      }
    >;

    DeployPool(
      pool?: string | null,
      poolCommitter?: null,
      ticker?: null
    ): TypedEventFilter<
      [string, string, string],
      { pool: string; poolCommitter: string; ticker: string }
    >;

    FeeChanged(
      fee?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { fee: BigNumber }>;

    FeeReceiverChanged(
      receiver?: string | null
    ): TypedEventFilter<[string], { receiver: string }>;

    GovernanceAddressChanged(
      oldAddress?: string | null,
      newAddress?: string | null
    ): TypedEventFilter<
      [string, string],
      { oldAddress: string; newAddress: string }
    >;

    InvariantCheckChanged(
      invariantCheck?: string | null
    ): TypedEventFilter<[string], { invariantCheck: string }>;

    MaxLeverageChanged(
      leverage?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { leverage: BigNumber }>;

    MintAndBurnFeesChanged(
      mint?: BigNumberish | null,
      burn?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { mint: BigNumber; burn: BigNumber }
    >;

    PoolKeeperChanged(
      _poolKeeper?: null
    ): TypedEventFilter<[string], { _poolKeeper: string }>;

    ProvisionalGovernanceChanged(
      newAddress?: string | null
    ): TypedEventFilter<[string], { newAddress: string }>;

    SecondaryFeeSplitChanged(
      fee?: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { fee: BigNumber }>;
  };

  estimateGas: {
    autoClaim(overrides?: CallOverrides): Promise<BigNumber>;

    claimGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployPool(
      deploymentParameters: {
        poolName: string;
        frontRunningInterval: BigNumberish;
        updateInterval: BigNumberish;
        leverageAmount: BigNumberish;
        settlementToken: string;
        oracleWrapper: string;
        settlementEthOracle: string;
        feeController: string;
        mintingFee: BigNumberish;
        changeInterval: BigNumberish;
        burningFee: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fee(overrides?: CallOverrides): Promise<BigNumber>;

    feeReceiver(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    governanceTransferInProgress(overrides?: CallOverrides): Promise<BigNumber>;

    invariantCheck(overrides?: CallOverrides): Promise<BigNumber>;

    isValidPool(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isValidPoolCommitter(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    numPools(overrides?: CallOverrides): Promise<BigNumber>;

    pairTokenBaseAddress(overrides?: CallOverrides): Promise<BigNumber>;

    poolBaseAddress(overrides?: CallOverrides): Promise<BigNumber>;

    poolCommitterBaseAddress(overrides?: CallOverrides): Promise<BigNumber>;

    poolKeeper(overrides?: CallOverrides): Promise<BigNumber>;

    pools(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    provisionalGovernance(overrides?: CallOverrides): Promise<BigNumber>;

    secondaryFeeSplitPercent(overrides?: CallOverrides): Promise<BigNumber>;

    setAutoClaim(
      _autoClaim: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFee(
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFeeReceiver(
      _feeReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setInvariantCheck(
      _invariantCheck: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPoolKeeper(
      _poolKeeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSecondaryFeeSplitPercent(
      newFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferGovernance(
      _governance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    autoClaim(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployPool(
      deploymentParameters: {
        poolName: string;
        frontRunningInterval: BigNumberish;
        updateInterval: BigNumberish;
        leverageAmount: BigNumberish;
        settlementToken: string;
        oracleWrapper: string;
        settlementEthOracle: string;
        feeController: string;
        mintingFee: BigNumberish;
        changeInterval: BigNumberish;
        burningFee: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    feeReceiver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governanceTransferInProgress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    invariantCheck(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isValidPool(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidPoolCommitter(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    numPools(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pairTokenBaseAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolBaseAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poolCommitterBaseAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    poolKeeper(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pools(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    provisionalGovernance(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    secondaryFeeSplitPercent(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAutoClaim(
      _autoClaim: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFee(
      _fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFeeReceiver(
      _feeReceiver: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setInvariantCheck(
      _invariantCheck: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPoolKeeper(
      _poolKeeper: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSecondaryFeeSplitPercent(
      newFeePercent: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferGovernance(
      _governance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
